# Generated by Django 5.1.7 on 2025-05-07 08:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowableMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('borrowing_date', models.DateField(null=True)),
                ('return_date', models.DateField(null=True)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('nb_current_borrowings', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(0)])),
                ('is_blocked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ParlourGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(default='jeu de société', max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('creator', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('borrowablemedia_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='librarians_app.borrowablemedia')),
                ('media_type', models.CharField(default='livre', max_length=150)),
                ('author', models.CharField(max_length=150)),
            ],
            bases=('librarians_app.borrowablemedia',),
        ),
        migrations.CreateModel(
            name='Cd',
            fields=[
                ('borrowablemedia_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='librarians_app.borrowablemedia')),
                ('media_type', models.CharField(default='cd', max_length=150)),
                ('artist', models.CharField(max_length=150)),
            ],
            bases=('librarians_app.borrowablemedia',),
        ),
        migrations.CreateModel(
            name='Dvd',
            fields=[
                ('borrowablemedia_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='librarians_app.borrowablemedia')),
                ('media_type', models.CharField(default='dvd', max_length=150)),
                ('director', models.CharField(max_length=150)),
            ],
            bases=('librarians_app.borrowablemedia',),
        ),
        migrations.AddField(
            model_name='borrowablemedia',
            name='borrower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='librarians_app.member'),
        ),
    ]
