# Generated by Django 5.1.7 on 2025-03-19 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librarians_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='borrowingDate',
            new_name='borrowing_date',
        ),
    ]
