# Generated by Django 5.1.7 on 2025-03-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarians_app', '0002_rename_borrowingdate_book_borrowing_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='media_type',
            field=models.CharField(default='book', max_length=150),
        ),
    ]
