# Generated by Django 5.1.7 on 2025-03-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarians_app', '0003_book_media_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='media_type',
            field=models.CharField(default='livre', max_length=150),
        ),
    ]
