# Generated by Django 5.1.7 on 2025-04-21 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librarians_app', '0005_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='blocked',
            new_name='is_blocked',
        ),
    ]
