# Generated by Django 5.1.7 on 2025-04-23 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarians_app', '0006_rename_blocked_member_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='borrower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='librarians_app.member'),
        ),
    ]
