# Generated by Django 5.1.7 on 2025-04-23 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarians_app', '0007_book_borrower'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='return_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='borrowing_date',
            field=models.DateField(null=True),
        ),
    ]
