# Generated by Django 5.1.7 on 2025-04-24 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarians_app', '0008_book_return_date_alter_book_borrowing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='borrower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='librarians_app.member'),
        ),
    ]
