# Generated by Django 5.1.7 on 2025-04-26 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarians_app', '0009_alter_book_borrower'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(default='cd', max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('artist', models.CharField(max_length=150)),
                ('borrowing_date', models.DateField(null=True)),
                ('return_date', models.DateField(null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('borrower', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='librarians_app.member')),
            ],
        ),
    ]
