# Generated by Django 5.1.7 on 2025-04-26 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarians_app', '0010_cd'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParlourGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(default='jeu de société', max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('creator', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Dvd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(default='dvd', max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('director', models.CharField(max_length=150)),
                ('borrowing_date', models.DateField(null=True)),
                ('return_date', models.DateField(null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('borrower', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='librarians_app.member')),
            ],
        ),
    ]
